### ISSUE TITLE
Create the ability to directly map a json response to an object

### ISSUE THREAD

**Issue by ryber** [OpenUnirest/unirest-java#11]
Should also support the ability to inject your own JSON mapper in a way similar to feign. In fact, look into just supporting feigns interface for this

**Comment by gimmebytes** [comment]
@ryber Hi Ryan!
I just wanted to say thanks for taking over unirest - we're heavily relying on the library and sadly it was abandonded by Mashape. If you need any help or input on planned enhancements let me know. Maybe I can help out.

Cheers,
Marvin

**Comment by djKianoosh** [comment]
Same here! Big thanks. Please let us know how we can help and keep this rolling.

**Comment by ryber** [comment]
Closing this one, splitting it up
