### ISSUE TITLE
Suggesting looking into another great Unirest fork

### ISSUE THREAD

**Issue by RoboFlax** [OpenUnirest/unirest-java#13]
Hey,

I would recommend forking/pullling/looking into @josueeduardo's unirest fork https://github.com/josueeduardo/rest-client and continuing to work at this point because all the much needed improvements were made there.

Otherwise, I think it would be a setback to discard so much improvements.

**Comment by ryber** [comment]
Oh wow, I had been looking for someone also also doing this and I didn't find that. HE has done many of the same things I was planning on. I do think it's important to build this in a open neutral place so we don't end up in the same situation that we were in before  and I am defiantly going to cherry pick improvements from his line into this one.

I'll also send a message to Josue to see if he wants to collaborate together. 

Thanks
1
