### ISSUE TITLE
Support Type References For DeSerialization

### ISSUE THREAD

**Issue by ryber** [OpenUnirest/unirest-java#19]
from https://github.com/Kong/unirest-java/issues/200

When I work with Spring RestTemplate class, I can use ParametrizedTypeReference instance to provide generic class to deserialization, like so:

```
ResponseEntity<ApiResponse<Payment>> response = template.exchange(request, new ParameterizedTypeReference<ApiResponse<Payment>>() {});
```

This is really nicely integrated in the overall code.

It would be nice to include a chapter on how to achieve this with Unirest. For example:

```
// Generic response type
HttpResponse response = Unirest.post(uri)
    .header("Accept", "application/json")
    .header("Content-Type", "application/json")
    .body(body)
    .asString();

ObjectMapper mapper = new ObjectMapper();
TypeReference<ApiResponse<Payment>> type = new TypeReference<ApiResponse<Payment>>() {};
ApiResponse<Payment> responseWrapper = mapper.readValue(response.getRawBody(), type);

```

Ideally, it would be nice to be able to provide some API where I can actually use type reference as a parameter, for example:
```
HttpResponse response = Unirest.post(uri)
    .header("Accept", "application/json")
    .header("Content-Type", "application/json")
    .body(body)
    .asObject(new TypeReference<ApiResponse<Payment>>() {});
```

**Comment by ryber** [comment]
cc @petrdvorak Hi, this is a fork attempting to pick up where Unirest left off.

The problem here is twofold:
   1. Unirest does not come with a json ObjectMapper, you have to supply that, it only has the original org.json package
   1. TypeReference is a Jackson thing and isn't standard java. In gson they use TypeToken to do the same thing, Spring similarly has yet another of this famous hack. 

Still there may be a way to pass one through to the Object Mapper. I'll take a look. If we can do it without taking sides then we will.

**Comment by petrdvorak** [comment]
While I understand this might require a wider community consensus, looking into the docs, I wouldn't mind having Guava (that provides own `TypeToken` class) as a provided dependency for Unirest. We add it in all our projects anyway...

If having the extra dependency is an issue, just adding this topic in documentation would help - I remember I spent too much time when dealing with this issue for the first time. (Currently, we have it resolved in our projects.)

**Comment by ryber** [comment]
Hi @petrdvorak, sorry this has taken a while to get to. I ended up implementing my own Generic Type Reference. You can see how it's used here:

https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/AsGenericTypeTest.java

This can be used with either Jackson like this:
https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/io/github/openunirest/http/JacksonObjectMapper.java#L44-L50

Or With Gson
https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/io/github/openunirest/http/JacksonObjectMapper.java#L44-L50

Or I suspect with any number of other mapping libraries.

2.4.00 should be in mvn central in about 20 minutes
