### ISSUE TITLE
Differences with the Kong Unirest

### ISSUE THREAD

**Issue by sic2** [OpenUnirest/unirest-java#27]
Hello!

I was linked this work, which seems to be very active recently. I am happy that someone is still putting work into this!

Can you possibly summarise what changes were made in this fork in terms of bugs fixed and new features? Thanks!

**Comment by ryber** [comment]
There is a changelog here: https://github.com/OpenUnirest/unirest-java/blob/master/CHANGELOG.md

I would be happy to answer any specific questions beyond that if you have them.

There has also been a lot of work done on the tests you may find useful https://github.com/OpenUnirest/unirest-java/tree/master/src/test/java/BehaviorTests

**Comment by ryber** [comment]
One note: 2.2.03 is currently working it's way through the magical maven central release process. Should be there by morning.
