### ISSUE TITLE
Question about multi-threading and multiple REST servers

### ISSUE THREAD

**Issue by CSBaum** [OpenUnirest/unirest-java#29]
Hi,

I just found this library and it looks like it would fit my application's needs, but as I am poking around I was wondering how well Unirest can handle being called multiple time concurrently each time connecting to a different REST server? 

 A bit of background about the application I am working on ... its primary purpose to query X number of application servers to gather their configuration information so that a user has a 'single pane of glass' view of all their application configurations.  From a numbers standpoint it needs to be able to reach out to 2 - 400 different servers concurrently.

Thanks in advance!

Sean

**Comment by ryber** [comment]
Hi Sean,
  Unirest is just a convince wrapper around Apache HTTP client. The apache client itself is where the heavy lifting happens. Internally HTTPClient has a number of different options for connection management which can be overwrote by setting the internal client yourself (https://github.com/OpenUnirest/unirest-java#custom-http-clients).

By default Unirest configures a PoolingHttpClientConnectionManager (http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/conn/PoolingHttpClientConnectionManager.html)

Which I think should probably be OK for your use, but again, the options are there for you to play with.

Good luck!

**Comment by ryber** [comment]
Oh, also, you can manipulate the pool with the Options. See https://github.com/OpenUnirest/unirest-java#concurrency
