### ISSUE TITLE
JSESSIONID Cookie is cached preventing multiple basic auth users

### ISSUE THREAD

**Issue by melloware** [OpenUnirest/unirest-java#30]
I reported this originally here:  https://github.com/Kong/unirest-java/issues/214

This is a bug issue for me where i want to use the same UniRest client to connect to multiple sites with different auth.

https://stackoverflow.com/questions/45304424/unirest-is-caching-basic-authentication-information

**Comment by ryber** [comment]
@melloware have you tried the most recent version of this version of Unirest? It does not cache against independent invocations:

https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/HeaderTest.java#L123-L161

If you are getting and reusing HttpRequest objects That might explain what you are experiencing but that's not really the intended use case. You should get a new HttpRequest object for each request.

**Comment by melloware** [comment]
I had not tested with this library but was eyeballing the code and I didn't see anything that would have fixed it.  But this unit test makes perfect sense and looks exactly fixed.

**Comment by ryber** [comment]
The code you were talking about is in HttpRequest, and you get a new HttpRequest request object each time you call the static verb methods.

**Comment by melloware** [comment]
OK using your latest library 2.2.07 i was able to reproduce my issue.   I have these two calls back to back....a GET and a POST with different users.

```java 
response = Unirest.get(url).basicAuth("user1","pass1").queryString(queryParameters).asJson();

response = Unirest.post(fullUrl).basicAuth("user2","pass2").fields(formParameters).asJson();
```

When the POST is called it still has the user1/pass1 instead of the new username and password set.

**Comment by ryber** [comment]
I'm sorry, I cannot reproduce this. I did produce a couple of tests that attempt to reproduce it:

https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/HeaderTest.java#L165-L194

One even goes across domains. 

I don't know how it could be cached. Unirest.get and Unirest.post produce new instances of different httprequest objects. 

Are you setting a custom Apache HttpClient ? It does some weird stuff with basic auth caching but it's typically by route. ... plus Unirest doesn't use it.

Can you produce a Unit test showing this behavior?

**Comment by melloware** [comment]
AHhh OK I think I am narrowing in on it...

1. 2 POST calls.

2. Same server with different routes  http://localhost:8080/rest/secure/route1 and http://localhost:8080/rest/secure/route2

3. If I inspect I can see you are setting the basic auth header correctly but inside HTTP client it looks like it reuses a HTTP connection or thread and when I inspect cookieStore it has the same JSESSIONID.  So its sending the JSESSIONID cookie and Jboss is looking up that session and knows it associated to the previous login.

So it like I need some way of clearing those cookies or something the DefaultHttpClient uses.

**Comment by melloware** [comment]
And I see in your Options class you are creating the instance of the HttpClient with defaults.  That one instance is why the Cookie is being reused on multiple requests.

**Comment by melloware** [comment]
I think you want to disable cookie management or make it an option somehow using the below disableCookieManagement() setting on HTTP client.

```java
HttpClient httpClient = HttpClientBuilder.create()
                        .disableCookieManagement()
                        .useSystemProperties()
                        .build();
```

**Comment by ryber** [comment]
huh, even if I have my mock server set a session and cookies, I still can't get it to do this. I don't doubt you through.

While I don't feel like a rest client in general should even manage session state, I'm also not keen on just changing it. I want to maintain backwards compatibility with the original Unirest. So I don't want to change the default behavior (even though I think it's silly)

I AM more than willing to add an option to turn it off.

**Comment by melloware** [comment]
Thanks for the quick turnaround. I will be in the office on Monday and will let you know how it goes!

**Comment by melloware** [comment]
You rock. I have confirmed this fixes my issue by setting `Options.enableCookieManagement(false);`

**Comment by ryber** [comment]
this is reflected in the old Kong unirest issue https://github.com/Kong/unirest-java/issues/214
