### ISSUE TITLE
Question: Is this supposed to be the new maintained repo?

### ISSUE THREAD

**Issue by xxRockOnxx** [OpenUnirest/unirest-java#32]
Asked because https://github.com/Kong/unirest-java is outdated compared to this one.

**Comment by ryber** [comment]
This is a fork that I've updated and maintained. as noted Kong has abandoned the main repo and the CIO has refused to let the community maintain it. 

Thanks for PR

**Comment by xxRockOnxx** [comment]
Shouldn't you mention that in the README or somewhere? Was actually confused a while ago if this was the new official repo.

Something like "Unofficial but maintained because..."

Not that important but really helps especially when there's like, 3 I think, repo when searching that has `unirest-java`. (Kong, mashape, and OpenUnirest)

**Comment by ryber** [comment]
I don't know that there is such a thing as "official" in open source. But yes, I have been meaning to write up a section like that as well as the guiding principles of this fork which differs from other forks (here backwards compatibility is a high priority)

also, FYI, Kong is the new name of Mashape
