### ISSUE TITLE
When Unirest restarts after shutdown it forgets any options that are set

### ISSUE THREAD

**Issue by jdbevan** [OpenUnirest/unirest-java#34]
Unirest can use the previously set options by modifying Options.setDefaults to only override the options/interceptors etc if they aren't set

**Comment by ryber** [comment]
So, question, my understanding of the original feature was that shutdown was something you tied to JVM shut down, it was not really intended to be something you did a lot. Are you regularly shutting it down and restarting inside the same JVM instance? If so, why?

**Comment by ryber** [comment]
Unirest is simply a big sugary wrapper around Apache Http Client. When you call shutdown Unirest in turn calls shutdown on 4 different Apache clients and threadmonitors which themselves are running various daemon threads. So calling shutdown on JVM exit is a good practice.

Once those components are shut down there is no restarting them. We need to fire up all new instances of them. Also each one is itself an option. So at best, we could only preserve ```some``` of the options during a re-init, not all, which might also be confusing. 

Which options were you setting?

**Comment by ryber** [comment]
2.2.12 is released and should be in maven central in 20-30 mintues
