### ISSUE TITLE
Multipart/Form-Data uploads are not using ISO-8859-1 which results in broken filenames.

### ISSUE THREAD

**Issue by ryber** [OpenUnirest/unirest-java#35]
Need example

**Comment by Catscratch** [comment]
Here's an example. We're using Jersey as server sided framework for deserialization.

`
@Test
public void testUTF8() throws UnirestException {
	String baseUrl = "http://myserver:8080/api/documents";
	InputStream fileData = new ByteArrayInputStream(new byte[] {'t', 'e', 's', 't'});
	final String filename = "fileäöü.pöf";

	HttpResponse<MyObject> response = Unirest.post(baseUrl)
			.field("file", fileData, filename)
			.asObject(MyObject.class);

	assertThat(response.getStatus(), is(201));
	assertThat(response.getBody().getFilename(), is(filename));
}
`

Here's a comment about a valid solution for this problem:
https://github.com/OpenUnirest/unirest-java/pull/33#issuecomment-412890167

The problem itself is that browser mode is not set and charset neither.

This example above results in Apache http mime library where not mode and charset are set. Therefor, apache chooses US_ASCII as default.

The right way to solve this would be to stick to RFC-7578.

**Comment by ryber** [comment]
2.2.11 should be in maven central soon. This should be working now:
https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/FormPostingTest.java#L379-L404
