### ISSUE TITLE
Add request/response logging capabilities.

### ISSUE THREAD

**Issue by LukaszTheProgrammer** [OpenUnirest/unirest-java#39]
I tried to achieve request/response logging with simple decorator of HttpClient but I failed to do that because request/response InputStream implementation allows to read them only once. I am able to log headers and status code or uri but it would be nice to log body of both rq and rs.
I wonder if there is anything like this feature in plan or it can be achieved with current version.

Regards
Lukasz

**Comment by ryber** [comment]
Unirest itself is just a wrapper around HttpClient. HttpClient has some pretty crazy levels of debug logging available, you just have to enable it:
https://hc.apache.org/httpcomponents-client-ga/logging.html

There are lots of options there.

Although they don't cover it in that doc you can enable all of this at runtime (before you fire up unirest) in code like I sometimes do in the tests:
https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/util/TestUtil.java#L92-L96

**Comment by LukaszTheProgrammer** [comment]
Thanks @ryber. I will have to look it up. My biggest concern right now is whether HttpClient allows to customize output format of the log message since my ELK stack requires some formatting to consume log entry properly.

**Comment by ryber** [comment]
Apache HttpClient works with SLF4J so you should be good. Just be careful, the debug logging can produce a LOT of logs. It will make your ELK stack sad
