### ISSUE TITLE
IllegalThreadStateException under high load

### ISSUE THREAD

**Issue by MrGraversen** [OpenUnirest/unirest-java#41]
Hi,

We are experiencing a hard-to-reproduce issue where OpenUnirest will throw an `IllegalThreadStateException` when under heavy load.

We have a service which will at times invoke OpenUnirest at high frequency to deliver webhooks, and this is when we sometimes run into this issue, which doesn't seem recoverable unless we roll the app.

I submitted a few comments in an [**ancient issue on Kong/unirest-java**](https://github.com/Kong/unirest-java/issues/92#issuecomment-161281363) about a similar issue with the `HttpClientHelper`, but I don't think it was looked into, ever.

The partial stack trace is as follows: 

```
java.base/java.lang.Thread.start(Thread.java:804)
io.github.openunirest.request.HttpClientHelper.asyncClient(HttpClientHelper.java:84)
io.github.openunirest.request.HttpClientHelper.requestAsync(HttpClientHelper.java:59)
io.github.openunirest.request.HttpClientHelper.requestAsync(HttpClientHelper.java:49)
io.github.openunirest.request.BaseRequest.asStringAsync(BaseRequest.java:64)
```

**Environment:**

* OpenUnirest version: 2.4.02
* `java --version`: java 10.0.2 2018-07-17
* `lsb_release -a`: Debian GNU/Linux 8.11 (jessie)
* `cat /proc/cpuinfo`: Intel(R) Xeon(R) CPU E5-2690 v4

**Comment by ryber** [comment]
@MrGraversen I added a synchronized on the actual start, along with a extra check. It's probably overkill. I never like using synchronized but I think it's the only good solution here. Can you try out 2.5.01 and let me know what you see? Should be in mvn central in a few minutes.

**Comment by MrGraversen** [comment]
Hi @ryber, thank you! I will upgrade our OpenUnirest version now.

**Comment by ryber** [comment]
Cool, let me know if it works so we can close this

**Comment by ryber** [comment]
Hey @MrGraversen I'm a little concerned about when you say "after the application has been running for a while". You generally only get into this exception when It's attempting to start the AsyncClient, which. In a normal running system should be done once. Still, it looks like it's the monitor thread that is throwing the issue so I've added a double check on that as well.

Are you doing shutdowns on the clients regularly? I wouldn't expect this code to get run so often, heavy load or not?

I just published 2.5.02 with an additional possible fix you can try. Should be in mvn central soon

I'm also going to be releasing 3.0 which is a pretty major overhaul of the configuration later this week and I'll make sure these fixes are included.

**Comment by ryber** [comment]
3.0.00 is also released. see https://github.com/OpenUnirest/unirest-java/blob/master/UPGRADE_GUIDE.md

**Comment by MrGraversen** [comment]
Hi again @ryber, I agree, but the apps are not being bounced very often.

We are currently experiencing the issue, and according to systemctl the app has ran for a while:

`Active: active (running) since Wed 2018-11-21 14:51:15 CET; 1 day 18h ago`

We will upgrade to 3.0.00 shortly.

**Comment by MrGraversen** [comment]
We will deploy the 3.0.00 upgrade to our production environment on Wednesday, then continue to monitor the issue. It happened again during the weekend and during this morning.

I have been wondering whether the issue could be related to the OS — since threads in Java are OS threads.

**Comment by MrGraversen** [comment]
The upgrade was deployed, but during the weekend, we got the same results, it seems.

This service has been running for a while: `since Thu 2018-11-29 09:12:27 CET; 3 days ago`, according to `systemctl`.

We're now seeing a large number of: `java.lang.IllegalStateException` with message: `Request cannot be executed; I/O reactor status: STOPPED`

At the following call stack:

```
org.apache.http.util.Asserts.check(Asserts.java:46)
org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
unirest.BaseRequest.requestAsync(BaseRequest.java:229)
unirest.BaseRequest.asStringAsync(BaseRequest.java:140)
```

For reference, this is the 3.0 Unirest setup we're using:

```
        Unirest.config()
                .concurrency(HardwareUtils.numberOfProcessors(), 1)
                .connectTimeout(defaultConnectionTimeout) // => 2500
                .socketTimeout(defaultSocketTimeout); // => 10000
```

**Comment by ryber** [comment]
Huh, well at least we get a better error message now. As you probably know Unirest is just a thin abstraction around ApacheHttpClient (and async client). 

This error happens when the ConnectionManager's I/O reactor has stopped for some reason. see this thread: http://httpcomponents.10934.n7.nabble.com/I-O-reactor-status-STOPPED-td29059.html

This can happen for a number of reasons, including runtime exceptions elsewhere. I'm going to see if I can make Unirest expect this possible error and then report the original error (apparently there is a audit log somewhere), and maybe restart the reactor.

**Comment by ryber** [comment]
@MrGraversen I pushed up 3.1.01 which detects when the Apache reactor has stopped and re-builds it. This would, in theory, allow your system to continue running but I think this will just mask some other issue you have.

The Apache HttpAsyncClient is getting shut down for some reason and if you are not doing it then something else is. Some theories:
   1. There could be some process in your JVM shutting down unmanaged daemon threads? Perhaps due to memory usage?
   1. A exception is happening inside the execution of the callback that Apache is unable to deal with and is causing the reactor to shut down (I have read this can be the case)

**Comment by MrGraversen** [comment]
Hi @ryber after we increased the JVM heap space, it seemed to relieve the issue somewhat, however we saw it this morning as well.

I will up the version to 3.2.02!

Thank you for the continued support 😊

**Comment by ryber** [comment]
The newest version will only mask your problem, and depending on timing you might see the error still sometimes. If you follow that Apache link above I think you will find there is a way to get to a log of the reason the reactor was stopped, but I suspect you will find that it's just Java trying to survive.
