### ISSUE TITLE
Make httpasyncclient dep optional

### ISSUE THREAD

**Issue by ebuildy** [OpenUnirest/unirest-java#43]
Since this not required to use the library (if you dont make async request), this is better to make this dep optional.

**Comment by ryber** [comment]
For many people the async path is the primary path used. For them, the "regular" client is the optional one. Forcing people to choose which way they want to use the library at the time of installing it is a bad user experience. Especially when you consider that this entire library is just a bunch of sugar on top of Apache.

I would recommend that if you don't want it, exclude it.
