### ISSUE TITLE
ClientFactory does not create a CloseableHttpAsyncClient with Encoding support

### ISSUE THREAD

**Issue by rgraebert** [OpenUnirest/unirest-java#50]
Hi,

I am just migrating from the mashable package and noticed that my async requests are not being processing correctly due to missing response content encoding handling. Digging into the ClientFactory, I noticed that something like 

		ab.addInterceptorLast(new RequestAcceptEncoding());
		ab.addInterceptorLast(new ResponseContentEncoding());

is missing. Is this intended? 

I noticed that libraries such as sardine (https://github.com/lookfirst/sardine) handle this with an enableCompression() function. (https://github.com/lookfirst/sardine/blob/d71beef1ffbf3df4095f5f59e5d46ceabb904191/src/main/java/com/github/sardine/impl/SardineImpl.java#L290)

Should I set my own httpasyncclient if I want content encoding? Or do you plan to update the client factory to support this? Any advise is appreciated.

Robert

**Comment by ryber** [comment]
Well, Part of the point of this project is to abstract away Apache which on it's own can be difficult to use. This is one example why. So, yea, I'd be happy to add this if it helps folks not have to think about the details. The Unirest Config does expose a method for adding interceptors. Have you tried adding these two interceptors to that to see if it solves your problems? In the mean time I can see if adding these by default causes any issues or maybe solves some other issues I'm aware of.

Can you give me some more information about which encodings in particular you are dealing with?

GZIP encoding in particular is a defect in the Apache HttpAsyncClient that Unirest has a hack around. According to the mailing list I found they were not going to fix it until 5 (which is still in beta). 

I plan on future versions of Unirest abstracting Apache even more to the point where we can swap out implementations to something better like the Java 9 HTTP client.

**Comment by rgraebert** [comment]
Hio Ryan,

Thanks for responding.

I tried using the Config object, but I can only add a HttpRequestInterceptor and no HttpResponseInterceptor. Maybe you can update the config API to also support response interceptors? In general, this would be nice as I am planning to track responses for logging purposes anyhow.

Also: I am also not sure if it makes a difference whether the interceptors are added to the front or back. So if the config should handle addInterceptorFirst / addInterceptorLast separately.

Regarding encoding, I am indeed interested in Gzip. So if you could add whatever the Unirest hack around is for that would be great.

BTW: for some background, I wanted to switch to the openunirest version because I saw some weird errors whenever I added a callback to the asJsonAsync. I guess for now, I will just use the kong version until gzip is supported by unirest.

Thanks

**Comment by ryber** [comment]
OpenUnirest should handle GZIP now and does so exactly like the Kong version does (as I don't think I've changed this at all). You can see it in some tests here: https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/GZipTest.java#L33-L49

It does so by looking at the content encoding header and if it's GZIP, wrapping the InputStream in a Decompressing one: https://github.com/OpenUnirest/unirest-java/blob/master/src/main/java/unirest/ApacheResponse.java#L73-L87

So if this isn't working for you, (and is in Kong), then I would view that as a defect. Can you give me some more information about how you are using it? Maybe a code snippet? are you using asObject, asString, etc? And if you can share the response headers in your example that would help as well.

**Comment by rgraebert** [comment]
This is what I do:

Future<HttpResponse<JsonNode>> future = Unirest.get("GZIP Service")
                  .header("Authorization", "Bearer " + accessToken)
                  .asJsonAsync();
 HttpResponse<JsonNode> response = future.get();
                      

When I step into the JsonNode, I can see that the content is gzip encoded and it fails to parse the Json. 

I just switched back the kong version and and there it works fine. I will dig a little to see what could be different.

**Comment by rgraebert** [comment]
If you look at 
https://github.com/Kong/unirest-java/blob/72a53ff8535fdb89f07c2982dbdaacb1302093da/src/main/java/com/mashape/unirest/http/HttpResponse.java#L84

The gunziping is happening for all response types, but if i don't misread the code in openunirest, BinaryResponse::getBody and not in StringResponse, JsonResponse, etc. 

Is that intended?

**Comment by ryber** [comment]
Those methods return the static readString which in turn calls the same getContentAsBytes(). I have several tests showing asString, asJson, etc doing GZIP 

https://github.com/OpenUnirest/unirest-java/blob/master/src/test/java/BehaviorTests/AsStringTest.java#L49-L69

I even debugged it just to prove to myself that I'm not crazy. So Im puzzled as to how the Kong version is different. I suspect it must have to do with how the headers are read. I'll dig into it more.

**Comment by ryber** [comment]
If you could possibly share the value of the Content-Encoding on the response it might help?

**Comment by ryber** [comment]
Wait! What version are you using? There were a few there where I attempted to switch entirely to Apache's EntityUtils.toString method and then found it didn't work with the Async Client because of that bug so I went back to the way Kong did it.

Those versions were I think 3.0.00-3.0.04 It was fixed in 3.0.05 but we are up to 3.1.02

**Comment by rgraebert** [comment]
I am was using 3.1.01, as 3.1.02 was not pushed to the repos yet.

Here ais a subset of my response headers:
"Transfer-Encoding" -> chunked
"Content-Encoding" -> gzip
"Vary" -> Accept-Encoding
"Content-Type" -> application/json;charset=utf-8

**Comment by ryber** [comment]
I'm not sure, I can't replicate this as a problem. All of the tests to my own Spark/Jetty server work and I also tried some other places that are also doing gzip (https://github.com/OpenUnirest/unirest-java/commit/2871307e661c3ee158824cd9aaba2fde0ffd14fb)

If you could provide a test somewhere on GitHub or elsewhere that can reproduce this I could look into it more.

**Comment by rgraebert** [comment]
Thanks for your investigation. Let me fix a couple of other issues and then try out openUnirest again to see where things go wrong. I should be able to get back tomorrow.

**Comment by rgraebert** [comment]
Quick Update: after updating to 3.1.02, I no longer see this problem. With 3.1.01 it is repro for me. But I am ok with just focusing on 3.1.02

**Comment by ryber** [comment]
ug, weird, thanks
