### ISSUE TITLE
Headers in original order, please

### ISSUE THREAD

**Issue by paul-hammant** [OpenUnirest/unirest-java#55]
Sure, keep them as a map. But in the Headers.Entry, maybe have a field which is the order of addition.

Then with streams fu and #54, then maybe I can reconstruct the headers in the order in which they were specified on the server in question :)

**Comment by ryber** [comment]
Are these headers of the same key value? because the HTTP spec says:

https://tools.ietf.org/html/rfc2616
```
The order in which header fields with differing field names are
   received is not significant. However, it is "good practice" to send
   general-header fields first, followed by request-header or response-
   header fields, and ending with the entity-header fields.

   Multiple message-header fields with the same field-name MAY be
   present in a message if and only if the entire field-value for that
   header field is defined as a comma-separated list [i.e., #(values)].
   It MUST be possible to combine the multiple header fields into one
   "field-name: field-value" pair, without changing the semantics of the
   message, by appending each subsequent field-value to the first, each
   separated by a comma. The order in which header fields with the same
   field-name are received is therefore significant to the
   interpretation of the combined field value, and thus a proxy MUST NOT
   change the order of these field values when a message is forwarded.
```

So if Unirest follows the best practice it should actually re-order the headers to follow the recommendation of the spec. Only in the case of having multiple of the same name would it honor a specific order.

**Comment by paul-hammant** [comment]
It **is** significant when you're writing a service-virtualization technology that purports to do **exactly** what the upstream server did. Recording and playback is a common feature of such things. I'm sure you'll understand that a correctness check in the SV-technology's own tests would want to confirm that exactness.  However, mine's a niche case, and I respect your right to say no and cite rfc2616. I'll work around it, or without it per that RFC

**Comment by ryber** [comment]
Keep in mind that Unirest isn't even a solo client. It's just a fancy wrapper for Apache HTTP Client. Even if I set the order I can't guarantee that Apache won't do something else with it.

**Comment by paul-hammant** [comment]
So, I'm asking for an extra field on `Headers.Entry` (an integer starting at 0 an going up for each one added). I'll reorder them myself if #54 is moved forward too. And it's not the headers I set in UnitRest that I'm worried about it is the ones coming back with the response.

**Comment by ryber** [comment]
closed in https://github.com/OpenUnirest/unirest-java/commit/e9a2203c54f611fa5f5dee8d365d7f3260cc726b

version 3.2.06
