### ISSUE TITLE
Support for weird HTTP verbs, please

### ISSUE THREAD

**Issue by paul-hammant** [OpenUnirest/unirest-java#56]
OK, so Subversion has a bunch of HTTP 1.1 verbs/methods that are not in the set you support (GET, POST, PUT, DELETE, PATCH, HEAD & OPTIONS).

Subversion also has: PROPFIND, REPORT, MKACTIVITY, PROPPATCH, CHECKOUT, MKCOL, MOVE, COPY, LOCK, UNLOCK, MERGE.

There's a case for a open spec'd name-your-own verb, but I'd be happy with the above.

**Comment by ryber** [comment]
oops, wrong one, repoening

**Comment by ryber** [comment]
This is done in 3.3.02:

lets say you want to use the word "CHEESE" as a method
```
   Unirest.request("CHEESE", "http://some.cheesy.thing")
          .asString();
```
