### ISSUE TITLE
Non-static config

### ISSUE THREAD

**Issue by paul-hammant** [OpenUnirest/unirest-java#57]
https://github.com/OpenUnirest/unirest-java#configuration shows some code snippets to do config that are static (pervasive for subsquent `Unirest.post(...)` invocations. 

Any chance on an **alternate** way of working where that config is instance based - rather than static/pervasive?  

```
unirest = Unirest.clientWithConfig().socketTimeout(500).build();
unirest.post(...)...
```

I appreciate there's `reset()` but that doesn't sit right with me having spend [a career fighting static state](http://www2.sys-con.com/itsg/virtualcd/java/archives/0812/hammant/index.html).

**Comment by gimmebytes** [comment]
How about creating a secondary instance, with a different configuration suiting your needs?

**Comment by ryber** [comment]
"it depends". Unirest has two underlying clients: an Apache HttpClient and a Apache HttpAsyncClient. Both are lazily constructed and both have threads that need to be shut down. 

In both cases Unirest creates a Idle Connection Monitor that scans for expired and idle connection and then releases them.

In the case of the AsyncClient, it also has a PoolingNHttpClientConnectionManager and the HttpAsyncClient itself (which I believe runs a IO event loop inside) both need to be shut down

**Comment by ryber** [comment]
going to close this one since non-static config can be done. If you see any issues with it let me know
